

List<List<String>> profile  =[
  [
    "Kiera",
    "assets/profile/p1.jpg",
    "Hi! how are you?",
    "2.5",
    "Google India",
  ],
  [
    "Jordyn",
    "assets/profile/p2.jpg",
    "What are you doing?",
    "4",
    "KPMG",
  ],
  [
    "Aniya",
    "assets/profile/p3.jpg",
    "Let's meet",
    "6",
    "NEC Corporation",
  ],
  [
    "Liliana",
    "assets/profile/p4.jpg",
    "Hi! how are you?",
    "1",
    "Infosys",
  ],
  [
    "Carolyn",
    "assets/profile/p5.jpg",
    "Let's meet",
    "8",
    "Tata Consultancy Services",
  ],
  [
    "Rachel",
    "assets/profile/p6.jpg",
    "What are you doing?",
    "5",
    "IBM",
  ],
  [
    "Alexis",
    "assets/profile/p7.jpg",
    "Hi! how are you?",
    "9",
    "Microsoft India",
  ],
  [
    "Kiera",
    "assets/profile/p1.jpg",
    "Hi! how are you?",
    "2.5",
    "Google India",
  ],
  [
    "Jordyn",
    "assets/profile/p2.jpg",
    "What are you doing?",
    "4",
    "KPMG",
  ],
  [
    "Aniya",
    "assets/profile/p3.jpg",
    "Let's meet",
    "6",
    "NEC Corporation",
  ],
  [
    "Liliana",
    "assets/profile/p4.jpg",
    "Hi! how are you?",
    "1",
    "Infosys",
  ],
  [
    "Carolyn",
    "assets/profile/p5.jpg",
    "Let's meet",
    "8",
    "Tata Consultancy Services",
  ],
  [
    "Rachel",
    "assets/profile/p6.jpg",
    "What are you doing?",
    "5",
    "IBM",
  ],
  [
    "Alexis",
    "assets/profile/p7.jpg",
    "Hi! how are you?",
    "9",
    "Microsoft India",
  ],
  [
    "Kiera",
    "assets/profile/p1.jpg",
    "Hi! how are you?",
    "2.5",
    "Google India",
  ],
  [
    "Jordyn",
    "assets/profile/p2.jpg",
    "What are you doing?",
    "4",
    "KPMG",
  ],
  [
    "Aniya",
    "assets/profile/p3.jpg",
    "Let's meet",
    "6",
    "NEC Corporation",
  ],
  [
    "Liliana",
    "assets/profile/p4.jpg",
    "Hi! how are you?",
    "1",
    "Infosys",
  ],
  [
    "Carolyn",
    "assets/profile/p5.jpg",
    "Let's meet",
    "8",
    "Tata Consultancy Services",
  ],
  [
    "Rachel",
    "assets/profile/p6.jpg",
    "What are you doing?",
    "5",
    "IBM",
  ],
  [
    "Alexis",
    "assets/profile/p7.jpg",
    "Hi! how are you?",
    "9",
    "Microsoft India",
  ],

];